# src/SIE/EquipementBundle/Resources/config/routing.yml
 
sie_equipement_homepage:
    path:     /
    defaults: { _controller: "SIEEquipementBundle:Default:index" }
       

get_all_cons:
    path:     /getAllConstructeur
    defaults: { _controller: "SIEEquipementBundle:Default:getConstructeurs" }
    methods:  [GET]
    
get_all_type:
    path:     /getAllType
    defaults: { _controller: "SIEEquipementBundle:Default:getType" }
    methods:  [GET]
    
sie_get_equipements:
    path:     /getEquipements/{id_central}
    defaults: { _controller: "SIEEquipementBundle:Admin:getEquipementsByIdCentral" }
    
get_equipement:
    path:     /getEquipement/{id_equipement}
    defaults: { _controller: "SIEEquipementBundle:Admin:getEquipement" }
    
get_all_equipement:
    path:   /getAll
    defaults: { _controller: "SIEEquipementBundle:Admin:getAll" }


add_equipement:
    path:     /addEquipement
    defaults: { _controller: "SIEEquipementBundle:Admin:getEquipement" }
    methods:  [POST]

del_equipement :
    path:     /delEquipement
    defaults: { _controller: "SIEEquipementBundle:Admin:getEquipement" }
    methods:  [POST]

update_equipement :
    path:     /updateEquipement
    defaults: { _controller: "SIEEquipementBundle:Admin:updateEquipement" }
    methods:  [POST]

get_access:
    path:     /getAccess/{id_equipement}/
    defaults: { _controller: "SIECentralBundle:Admin:getAccess" }
    methods:  [GET]

    